admin_menu_create:
    path: /create/{parent_id}
    defaults:
        _controller: \Mindy\Bundle\MenuBundle\Controller\Admin\MenuController::create
        parent_id: null
    requirements:
        parent_id: \w+

admin_menu_update:
    path: /update/{id}
    defaults:
        _controller: \Mindy\Bundle\MenuBundle\Controller\Admin\MenuController::update
    requirements:
        id: \d+

admin_menu_remove:
    path: /remove/{id}
    defaults:
        _controller: \Mindy\Bundle\MenuBundle\Controller\Admin\MenuController::remove
    requirements:
        id: \d+

admin_menu_list:
    path: /list/{parent_id}
    defaults:
        _controller: \Mindy\Bundle\MenuBundle\Controller\Admin\MenuController::list
        parent_id: null
    requirements:
        parent_id: \w+
